[project]
name = "hajimeteno-prophet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prophet>=1.1.6",
    "notebook>=7.3.1",
    "pandas>=2.2.3",
]
